### ISSUE TITLE
panic: runtime error: index out of range [193] with length 193

### ISSUE THREAD

**Issue by gian9959** [Lofter1/anyflip-downloader#13]
When trying to dowload a specific file I get this runtime error:

```
panic: runtime error: index out of range [193] with length 193
goroutine 1 [running]:
main.prepareDownload(0xc00018e900)
	/home/runner/work/anyflip-downloader/anyflip-downloader/main.go:106 +0x43c
main.main()
	/home/runner/work/anyflip-downloader/anyflip-downloader/main.go:52 +0x1c
```
Tried both on Linux and Windows, tried compiling from source and using the release.
Does not happen with any other file I tried downloading, only with this specific one.

**Comment by gian9959** [comment]
The issue seems to be inside configjs.go in the function getPageFileNames. The array matches seems to go out of bounds at 193, but the pages in this document are actually 258. I dowloaded documents with up to 257 pages without having this problem.

**Comment by gian9959** [comment]
the problems seems to be in configjs,go in the function getPageFileNames caused by the array "matches".
The file I am trying to download has 258 pages, but weirdly there are only 193 jpgs names listed in the config.js on the website.
Infact, if I try to load the thumbnails of the pages on AnyFlip, the thumbnails only load up to page 192.
I have no idea how to solve this or if there is a workaround.

**Comment by gian9959** [comment]
I managed to download the file by appending a slice with the names of the other pages starting from 194.jpg to "pageFilesNames".
Apparently, the missing page names were replaced by the standard page number names after page 193.
So this Issue is just to let people know that there are documents on AnyFlip that have pages with random names and page number names on the same document.

**Comment by Lofter1** [comment]
Sorry for replying so late. Interesting. If you by any chance still have the config.js file for this book, I would be happy to have a look at it and see if I can find a solution for this issue.

**Comment by Fra-cyber-9** [comment]
I got the same problem, but this way

panic: runtime error: index out of range [1] with length 1
goroutine 1 [running]:
main.sanitizeURL(0xc00013ea20)
        /home/runner/work/anyflip-downloader/anyflip-downloader/main.go:116 +0xf4
main.prepareDownload(0xc00013ea20)
        /home/runner/work/anyflip-downloader/anyflip-downloader/main.go:78 +0x46
main.main()
        /home/runner/work/anyflip-downloader/anyflip-downloader/main.go:52 +0x1c5
I don’t know which command to put but my file has 121 pages. If anyone can help me.
